Update Windows os image
PlayFab/MpsAgent pull request #181
Opened 2024-04-01 22:58 UTC by valexao

updated image tag for windows os image

2024-04-01 23:07 UTC, dgkanatsios approved these changes

2024-04-01 23:08 UTC, dgkanatsios requested changes
Do we need this extra file?

2024-04-02 00:30 UTC, valexao commented
not sure what this file is but looks like it will not be checked in? seems like some github beta view thing 
![image](https://github.com/PlayFab/MpsAgent/assets/46427879/da60dc9f-9ce3-4a40-b8b7-08d3fa2b1c96)

2024-04-02 02:10 UTC, dgkanatsios commented
Looks like the PR has two files, we should remove the two in the "LocalMultiplayerAgentPublishFolder"

2024-04-02 21:04 UTC, dgkanatsios approved these changes

2024-04-02 21:06 UTC, merged